export const TODO_REQUEST = "TODO_REQUEST"
export const TODO_REQUEST_SUCCESS = "TODO_REQUEST_SUCCESS"
export const TODO_REQUEST_FAIL = "TODO_REQUEST_FAIL"


export const GET_TODO_REQUEST = "GET_TODO_REQUEST"
export const GET_TODO_REQUEST_SUCCESS = "GET_TODO_REQUEST_SUCCESS"
export const GET_TODO_REQUEST_FAIL = "GET_TODO_REQUEST_FAIL"

export const GET_SINGLE_TODO_REQUEST = "GET_SINGLE_TODO_REQUEST"
export const GET_SINGLE_TODO_REQUEST_SUCCESS = "GET_SINGLE_TODO_REQUEST_SUCCESS"
export const GET_SINGLE_TODO_REQUEST_FAIL = "GET_SINGLE_TODO_REQUEST_FAIL"

export const UPDATE_SINGLE_TODO_REQUEST = "UPDATE_SINGLE_TODO_REQUEST"
export const UPDATE_SINGLE_TODO_REQUEST_SUCCESS = "UPDATE_SINGLE_TODO_REQUEST_SUCCESS"
export const UPDATE_SINGLE_TODO_REQUEST_FAIL = "UPDATE_SINGLE_TODO_REQUEST_FAIL"

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST"
export const DELETE_TODO_REQUEST_SUCCESS = "DELETE_TODO_REQUEST_SUCCESS"
export const DELETE_TODO_REQUEST_FAIL = "DELETE_TODO_REQUEST_FAIL"

export const DELETE_SINGLE_TODO_REQUEST = "DELETE_SINGLE_TODO_REQUEST"
export const DELETE_SINGLE_TODO_REQUEST_SUCCESS = "DELETE_SINGLE_TODO_REQUEST_SUCCESS"
export const DELETE_SINGLE_TODO_REQUEST_FAIL = "DELETE_SINGLE_TODO_REQUEST_FAIL"

